config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  #get    '/about',   to: 'static_pages#about'
  #get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :chores, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chore.rb
class Chore < ApplicationRecord
  belongs_to :user

  #default_scope -> { order(created_at: :desc) }

  validates  :user_id,          presence: true
  validates  :description,      presence: true, length: { maximum: 255 }
  validates  :time_to_complete, presence: true, numericality: true
  validates  :priority,         presence: true, inclusion: { in: %w(3-Low 2-Medium 1-High), message: "%{ value } is not a valid priority level" }

  #def self.complete_this_chore(user)
    #Chore.order("RANDOM()").first.description if Chore
  #  if Chore.any?
  #    this_chore = Chore.unscoped.where(user: user).order("RANDOM()").first
  #  end
  #end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :chores, dependent: :destroy

    attr_accessor :available_time
     
    before_save { self.email = email.downcase } # email addresses are down cased by default to address case sensitivity

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

    validates :name, 
               presence:   true, 
               length:   { maximum: 50 }

    validates :email, 
               presence:     true, 
               length:     { maximum: 200 }, 
               format:     { with: VALID_EMAIL_REGEX },
               uniqueness: { case_sensitive: false }

    has_secure_password

    validates :password, 
               presence:  true, 
               length:  { minimum: 9 },
               allow_nil: true

    # Returns the hash digest of a string argument
    def User.digest(string)
        # Cost is the variable that BCrypt uses to determin how complex to make the password digest. 
        # Here we are assigning the lowest value to cost as possible to speed up testing.
        # The value of cost is the minimum cost if it is actually the minimum cost otherwise assign the value of Engine.cost
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost

        # Create the hashed password based on the minimum cost
        BCrypt::Password.create(string, cost: cost)
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private

  def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Chordle needs you to log in"
        redirect_to login_url
      end
    end
end

app/controllers/chores_controller.rb
class ChoresController < ApplicationController
    before_action :logged_in_user, only: [:create, :destroy]

    def create
        @chore = current_user.chores.build(chore_params)
        #@chordle_says   = current_user.chores.where("time_to_complete <= ?", @available_time).order(priority: :asc).first.description
        if @chore.save
            flash[:success] = "Chordle added a new chore to your list!"
            redirect_to current_user
        end
    end

    def destroy
        @chore = Chore.find(params[:id])
        #@chordle_says   = current_user.chores.where("time_to_complete <= ?", @available_time).order(priority: :asc).first.description
        @chore.destroy
        flash[:success] = "Chordle removed a chore to your list!"
        redirect_to current_user
    end


    private

    def chore_params
        params.require(:chore).permit(:description, :priority, :time_to_complete)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      log_in user
      redirects_back_or_to user
    else
      flash.now[:danger] = "Invalid email/password combination"
      render 'new'
    end
  end

  def destroy
    log_out
    flash[:success] = "You have been logged out!"
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :show, :edit, :update, :destroy]
  before_action :correct_user,   only: [:show, :edit, :update]
  before_action :admin_user,     only: [:index, :destroy]

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user           = User.find(params[:id])
    @chores         = @user.chores.paginate(page: params[:page])
    @chore          = current_user.chores.build#(chore_params)
    @available_time = params[:available_time]
    #collect tasks with available time, order by priority, and take the top priority results
    if current_user.chores.any?
      @chordle_says = current_user.chores.where("time_to_complete <= ?", @available_time).order(priority: :asc).first#.description
    end
  end
  

  def new
    @user = User.new
  end


  def create
    @user = User.new(user_params)

    if @user.save
      log_in(@user)
      flash[:success] = "Let's get busy!"
      redirect_to @user
    else
      render 'new'
    end
  end


  def edit
    @user = User.find(params[:id])
  end


  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      flash[:success] = "Chordle has been updated!"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end


  private

    def user_params
      params[:user].permit(:name, :email, :password, :password_confirmation, :available_time)
    end

=begin
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Chordle needs you to log in"
        redirect_to login_url
      end
    end
=end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    # Return the full title on a per page basis
    def complete_title(page_title = '')
        base_title = "Chordle"

        if page_title.empty?
            base_title
        else
            page_title + " | " + base_title
        end
    end
    
end

app/helpers/chores_helper.rb
module ChoresHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        # Create a temporary cookie with the session method tied to the user id
        session[:user_id] = user.id
    end

    def current_user
        # Current_user equals current_user if it is not nil, otherwise it is assigned the value of the find_by method
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
        # Return true if the current_user.nil? returns false
        !current_user.nil?
    end

    def log_out
        session.delete(:user_id)
        @current_user = nil
    end

    # Redirects to stored or default location
    def redirects_back_or_to(default_page)
        redirect_to (session[:forwarding_url] || default_page)
        session.delete(:forwarding_url)
    end

    # Stores the url to be accessed
    def store_location
        session[:forwarding_url] = request.original_url if request.get?
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user, options = { size: 80 })
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{ gravatar_id }?s=#{ size }"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/chores/_chore.html.erb
<li id="chore-<%= chore.id %>">
    <%# link_to gravatar_for(chore.user, size: 50), chore.user %>
    <!--span class="user"><%# link_to chore.user.name, chore.user %></span-->
    <h4 class="description"><%= chore.description %></h4>
    <span class="priority">
        <b>Priority level:</b> <%= chore.priority %>
    </span>
    <span class="time_to_complete">
        <b>Estimated time needed to complete this chore:</b> <%= chore.time_to_complete %> minutes
    </span>
    <!--span class="timestamp">
        Added <%# time_ago_in_words(chore.created_at) %> ago.
    </span-->
    <%= link_to "Delete", chore, method: :delete, data: { confirm: "Are you sure?" } %>
</li>

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        Chordle by Azuredin Digital, copyright 2018 
    </small>

    <nav>
        <ul>
            <!--li><%#= link_to "About",   about_path %></li-->
            <!--li><%#= link_to "Contact", contact_path %></li-->
            <strong>Send feedback to:</strong> <%= mail_to "feedback@chordle.com" %>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <%= link_to "Chordle", root_path, id: "logo" %>

        <nav>
            <ul class="nav navbar-nav navbar-right" id="navbar-links">
                <% if logged_in? %>
                    <li><%= link_to "Users", users_path %></li>
                    <li><%= link_to "Profile", current_user %></li>
                    <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                    <li><%= link_to "Log out", logout_path, method: :delete %></li>
                <% else %>
                    <li><%= link_to "Home",   root_path %></li>
                    <!--li><%#= link_to "About",  about_path %></li-->
                    <li><%= link_to "Log in", login_path %></li>
                <% end %>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= complete_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <% flash.each do |message_type, message| %>
       <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <%= yield %>
      
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_chore_form.html.erb
<%= form_for @chore, url: { action: "create", controller: "chores" } do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <div class="field">
        <%= f.text_area    :description,      placeholder: "Tell Chordle all about your chore..." %>
        <%= f.text_field   :priority,         placeholder: "And is this chore a 1-High, 2-Medium, or 3-Low priority?" %>
        <%= f.number_field :time_to_complete, placeholder: "How many minutes do you think it will take you?" %>
    </div>
    <%= f.submit "Create chore", class: "btn btn-primary" %>
<% end %>

app/views/shared/_chore_modal.html.erb
<!-- Trigger the modal with a button -->
<%= button_tag 'Receive a chore modal style', class:'btn btn-warning', data: { toggle: ("modal"), target: ("#myModal")} %>
<!--utton type="button" class="btn btn-warning" data-toggle="modal" data-target="#myModal">Open Modal</button-->

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Chordle says:</h4>
      </div>
      <div class="modal-body">
        <p><%= @chordle_says %></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
        <div class="alert, alert-danger">
         This form contains <%= pluralize(object.errors.count, "error") %>.
        </div>

        <ul>
            <% object.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/shared/_user_available_time.html.erb
<%= form_tag({ controller: "users", action: "show" }, method: "get") do %>
    <%= select_tag "available_time", options_for_select([5, 10, 15, 20, 25, 30, 45, 60, 75, 90, 120]), prompt: "How many minutes do you have?" %>
    <%= submit_tag 'Submit', class: "btn btn-success" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "check out my chores!", current_user %></span>
<span><%= pluralize(current_user.chores.count, "chore") %></span>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<h1>Learn about Chordle!</h1>
<hr>
<p>Chordle is an app on a mission to make your life easier and less stressful.</p> 
<p>We take all the anxiety out of choosing which chore to do and instead randomly assign that chore to you!</p>
<p>Say word, son!</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>

<h1>Contact us</h1>

<hr>

<p>We are in here killin it b!</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
    <%#= image_tag  "chorebot_home.svg" %>
    <h1>Hello. My name is Chordle.</h1>

    <h2>Stop feeling overwhelmed by the todo list and start getting stuff done.</h2>

    <%= link_to "Let me help!", signup_path, class: "btn btn-lg btn-home" %>
</div>

<hr>

<h3>How it works:</h3>

<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4">
        <div class="panel panel-default">
            <div class="panel-heading">Add a chore.</div>
            <div class="panel-body">
                Give Chordle a chore and how long you think it will take to complete it.
            </div>
        </div>
    </div>

    <div class="col-lg-4 col-md-4 col-sm-4">
        <div class="panel panel-default">
            <div class="panel-heading">Give me some time...</div>
            <div class="panel-body">
                Let Chordle know about how much time you have to get some work done.
            </div>
        </div>
    </div>

    <div class="col-lg-4 col-md-4 col-sm-4">
        <div class="panel panel-default">
            <div class="panel-heading">Receive a chore!</div>
            <div class="panel-body">
                Chordle with give you a random chore to complete within the allotted time.
            </div>
        </div>
    </div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user, url: yield(:url_option)) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>

    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>

    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>

    <%= f.submit yield(:button_label), class: "btn" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<% provide(:button_label, "Save changes") %>
<% provide(:url_option, user_path(@user)) %>

<h1>Edit your account details</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= render "form" %>

        <div class="gravatar_edit">
            <%= gravatar_for @user %>
            <a href="http://gravatar.com/emails" target="_blank" rel="noopener">change</a>
        </div>
    </div>
</div> 

app/views/users/index.html.erb
<% provide(:title, "All users") %>

<h1>All Users</h1>

<%= will_paginate %>

<ul class="users">
    <% @users.each do |user| %>
        <li>
            <%= gravatar_for user, size: 50 %>
            <%= link_to user.name, user %>
            <% if current_user.admin? && !(user == current_user)%>
                | <%= link_to "delete", user, method: :delete, data: { confirm: "Chordle will delete this user" } %>
            <% end %>
        </li>
    <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<% provide(:button_label, "Create an account") %>
<% provide(:url_option, signup_path) %>

<div class="signup-page">
    <h1 class="signup-heading">Sign up for Chordle!</h1>

    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <%= render "form" %>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
    <aside class="col-md-4">
        <section class="user-info">
            <h1>
                <%= gravatar_for @user %>
                <%= @user.name %>
            </h1>
        </section>
        <section class="chore_form">
            <%= render 'shared/chore_form' %>
            <%= render 'shared/user_available_time' %>
            <%= link_to 'Receive a chore', '#', class: "btn btn-warning chore-button", data: { confirm: ("Chordle says: #{ @chordle_says.description } ") } %>
        </section>
    </aside>
    <main class="col-md-8">
        <% if @user.chores.any? %>
            <h3>Chores (<%= @user.chores.count %>)</h3>

            <ol class="chores">
                <%= render @chores %>
            </ol>

            <%= will_paginate @chores %>
        <% end %>
    </main>
</div>